version: '2'
services:
  zookeeper:
      image: zookeeper
      hostname: zookeeper
      ports:
        - 2181:2181
      environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=0.0.0.0:2888:3888
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      HOST_NAME: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/spafka/kafka:/kafka

  redis:
       image: redis:3.2
       restart: always
       ports:
             - "6379:6379"

  mysql:
       image: mysql:5.7
       restart: always
       environment:
             MYSQL_ROOT_PASSWORD: root
       volumes:
         - /Users/spafka/mysql:/var/lib/mysql
       ports:
         - "3306:3306"